### ISSUE TITLE
Add unicode symbols for different file types

### ISSUE THREAD

**Issue by arijit79** [willdoescode/nat#1]
You can add some Unicode symbols to each type of item. For example, an icon for a plain text file, a different one for a folder, something else for a symlink. You could also provide a command line flag to turn it off just in case someone uses a font that doesn't support symbols and weird boxes appear in place of the symbols

**Comment by willdoescode** [comment]
I have different colors for files and dirs I think unicode symbols would make them hard to read.

**Comment by arijit79** [comment]
I didn't get your point. The symbols are going to be seperated from the file information. What could make it hard to read

**Comment by willdoescode** [comment]
I feel like it would clutter up the file names. Feel free to submit a pull request with an image of how it would look with the unicode symbols.
