### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by phpguru** [willdoescode/nat#10]
I downloaded nat v1.0.7, sudo mv it to /usr/local/bin, chmod +x /usr/local/bin/nat and run nat
```
$ nat
bash: /usr/local/bin/nat: cannot execute binary file: Exec format error
```
I am on Ubuntu 20

**Comment by phpguru** [comment]
Relates to #4

**Comment by willdoescode** [comment]
Try compiling it yourself with `cargo build --release` and add the nat executable from target/release to your path
