### ISSUE TITLE
Latest 1.0.8 binary shows version number 1.0.7

### ISSUE THREAD

**Issue by nils-ohlmeier** [willdoescode/nat#14]
Just downloaded https://github.com/willdoescode/nat/releases/download/v1.0.8/nat.macOs.binary
When executing: nat -h it shows:

`nat 1.0.7
the ls replacement you never knew you needed
`

**Comment by willdoescode** [comment]
Forgot to update the version number before compiling to release. Will be fixed in the next release.

**Comment by willdoescode** [comment]
edited the release and added a new binary with the updated version. [here](https://github.com/willdoescode/nat/releases/tag/v1.0.8) Thread closed.
