### ISSUE TITLE
For gods sake, move the users and groups to the left where they belong to

### ISSUE THREAD

**Issue by DennisHeine** [willdoescode/nat#15]
This way it is too hard for an admin to read.
An please, please, don't say that you want to replace a tool in the LSB.

**Comment by willdoescode** [comment]
where would you like the users and groups to be relative to other file info?

**Comment by DennisHeine** [comment]
Hey :)
it would be easier to read if they were directly right of the rights. This way, info would be easier to focus on. Currently, one has to remember the username before looking to the access flags.

**Comment by willdoescode** [comment]
I will look into changing the position of the user and groups.
