### ISSUE TITLE
Feature request: widescreen layout

### ISSUE THREAD

**Issue by rcrane** [willdoescode/nat#19]
For directories with ~100 of files the table layout becomes tricky and requires the user to manually scroll the screen.
'ls' by default uses the window space by adding as many columns as possible and offers more overview that way.
After all, a widescreen is probably the default setup.
Making use of the available window space would increase usability of nat as well.
Maybe it's an option to show two tables next to each other if the space is sufficient.
Not sure if dynamic layouts are possible that way.

Btw: "nat | more" produces output hickups by adding empty lines.

**Comment by willdoescode** [comment]
widescreen mode would just be a matter of not printing new lines. Ill add a flag for it in the next release.

**Comment by willdoescode** [comment]
I am reopening this issue to say that I am working on it right now

**Comment by willdoescode** [comment]
added in the latest push, will be included in the next release.
