### ISSUE TITLE
Differences of unsigend numbers 

### ISSUE THREAD

**Issue by Th1nkP1nk** [willdoescode/nat#21]
There are some calculations with unsigned integers that may lead to unintended behavior.
E.g., try with a group name with less than 5 characters.
```rust 
draw_headline("group",get_group_by_gid(get_current_gid()).unwrap().name().to_str().unwrap().len() - 5, true);
```

**Comment by willdoescode** [comment]
This should be an easy fix by getting the largest group name size inside the directory and subtracting the length of the current file from it.
