### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by rennefJ** [willdoescode/nat#24]
The tool does not work for me.
Downloaded and put into /usr/local/bin and changed permissions to 755
When I run it, it just puts lines on my screen.
I am using macOS 10.15.7
<img width="1123" alt="Bildschirmfoto 2020-10-24 um 22 23 37" src="https://user-images.githubusercontent.com/34066534/97092849-9c8e6980-1647-11eb-89c8-8fbafcbff2f9.png">

**Comment by willdoescode** [comment]
this is an issue with a range it will be fixed soon.

**Comment by a0n** [comment]
i got the same issue here on archlinux

**Comment by willdoescode** [comment]
I have fixed the issue and once I rework the permissions output I will push a new build

**Comment by a0n** [comment]
now it works for me, nice!
