### ISSUE TITLE
Printing infinite underscores

### ISSUE THREAD

**Issue by Gnarflord** [willdoescode/nat#25]
When executing `nat` it prints the header correctly but get's stuck printing an infinite amount of underscore characters (Actually not the ASCII underscore character '_' but the space character with some terminal drawing shenenigans). Has to be killed with ^C

My guess would be that the function call `draw_headline("group",get_group_by_gid(get_current_gid()).unwrap().name().to_str().unwrap().len() - 5, true);` calls `draw_headline` with a negative line_length so the for-loop runs indefinitely? Not sure though, I haven't looked too closely at the source code.

![2020-10-24T22:10:59_pngquant](https://user-images.githubusercontent.com/19466442/97092651-3567b980-1635-11eb-8759-6b491b7ef7ba.png)

OS: Arch Linux
Tested terminal emulators: termite and tmux
I tried both: The provided binary as well as building [nat-git](https://aur.archlinux.org/packages/nat-git/) from the AUR via `yay -S nat-git`

**Comment by willdoescode** [comment]
That is one of the issues the next build will fix, I have other issues that I have to solve before I make a new build so It should be fixed in a little bit.
