### ISSUE TITLE
Distribute as a package

### ISSUE THREAD

**Issue by 13hannes11** [willdoescode/nat#3]
It would be great to be able to install via flatpak, snap and for example `apt install` command.

**Comment by tueksta** [comment]
or brew :)

**Comment by willdoescode** [comment]
Nat currently does not meet the requirements for brew as the repo is not 30 days old yet. as for flatpack and other linux package managers nat also does not yet meet the requirements.

**Comment by tsamartino** [comment]
Second brew support!  I'll install and try it out once it meets those requirements :)

**Comment by willdoescode** [comment]
cool! :) I will reopen this thread once it does.

**Comment by spikecodes** [comment]
I agree with adding brew, apt or flatpak support! For ArchLinux users, I've published it on the AUR (Arch User Repository) as [`nat-git`](https://aur.archlinux.org/packages/nat-git). You can install with:
```shell
yay -S nat-git
```

**Comment by willdoescode** [comment]
Like I said before I need to wait until this repo is 30 days old before I am able to add nat to brew.

**Comment by willdoescode** [comment]
thank you for publishing the package on AUR @spikecodes

**Comment by spikecodes** [comment]
> Like I said before I need to wait until this repo is 30 days old before I am able to add nat to brew.

Gotcha.

**Comment by willdoescode** [comment]
I have added natls to homebrew
simply run
```brew tap willdoescode/homebrew-natls```
and then 
```brew install natls```
