### ISSUE TITLE
Doesn't draw a headline as in the pictures

### ISSUE THREAD

**Issue by Gnarflord** [willdoescode/nat#30]
I guess the boolean `headline_on` is `false` for some reason?
Here's a screenshot:
![image](https://user-images.githubusercontent.com/19466442/97101230-902ffe00-1693-11eb-9b50-90533e1f98c7.png)

OS: Arch Linux
Tested terminal emulator: termite, xterm
nat version: 1.0.9

**Comment by SubOptimal** [comment]
With version 1.0.9 the headline is not shown anymore by default. To show it the option `-l` must be passed.

```
nat 1.0.9
the ls replacement you never knew you needed

USAGE:
    nat [FLAGS] [OPTIONS] [path]

FLAGS:
    -h, --help        Prints help information
    -l, --headline    enable the headline
    -V, --version     Prints version information

OPTIONS:
    -f, --file <file>    File to search for [default: ]

ARGS:
    <path>    Give me a directory [default: .]
```

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/issues/30#issuecomment-716113742
