### ISSUE TITLE
Suggestion: hide hidden files without -a option like ls

### ISSUE THREAD

**Issue by iwishiwasaneagle** [willdoescode/nat#31]
Standard `ls` doesn't show hidden files without the `-a` option. This is definitely something nat should consider implementing.
![image](https://user-images.githubusercontent.com/12383029/97103753-60d6bc80-16a6-11eb-8a72-b33c48a41d30.png)

**Comment by willdoescode** [comment]
Thats a good idea I will work on adding that

**Comment by willdoescode** [comment]
do you think it would be better if hidden files were shown with -a or if they were hidden?

**Comment by iwishiwasaneagle** [comment]
If you want to Nat to be a ls replacement, it's probably best to replicate
its behaviour

**Comment by willdoescode** [comment]
sounds good.

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/commit/8fa1eaffe31888248e03969bca7a6230ba2a8134

**Comment by willdoescode** [comment]
![Screen Shot 2020-10-25 at 11 47 55](https://user-images.githubusercontent.com/53620720/97116054-eca51480-16b7-11eb-9ee4-27394cd8d488.png)
