### ISSUE TITLE
Suggestion: Add to homebrew

### ISSUE THREAD

**Issue by rennefJ** [willdoescode/nat#32]
It would be great if I could install nat via homebrew. This would make it much easier to update to new versions.
Maybe you could add a tap to homebrew. Since nat is already on github this should be easy.
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by willdoescode** [comment]
#3 I can't yet as the nat repo is less than 30 days old.

**Comment by willdoescode** [comment]
I have added it to homebrew.
run 
```brew tap willdoescode/homebrew-natls```
and then
```brew install natls```
