### ISSUE TITLE
headline not in correlation with columns

### ISSUE THREAD

**Issue by kobibarhanin** [willdoescode/nat#35]
First - very nice cli!

It seems that when using the -l flag: 
`nat -l`
I get the headline not in sync:
![image](https://user-images.githubusercontent.com/34001701/97167887-3d883c00-1790-11eb-863b-720e1661160b.png)

I'm running on macOSX using Iterm2 and zshell.

**Comment by willdoescode** [comment]
I am working on a fix for that now.
