### ISSUE TITLE
Request: publish to crates.io

### ISSUE THREAD

**Issue by figsoda** [willdoescode/nat#37]
`cargo install --git https://github.com/willdoescode/nat --tag v1.2.1` does work but it's too long and doesn't work well with [cargo-update](https://github.com/nabijaczleweli/cargo-update). 

It would be nice to have it published to [crates.io](https://crates.io).

**Comment by willdoescode** [comment]
done. As the name nat was taken 2 years ago I have opted for natls. To install simply do 
```bash
cargo install natls
```
