### ISSUE TITLE
Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

### ISSUE THREAD

**Issue by saucer-man** [willdoescode/nat#38]
First of all thanks for such a good tool, I try to install this tool on ubuntu20:
```
apt-get install rustc cargo
cargo install natls
```
But when I try to execute it, it says I don't have permission.
```
$ ~/.cargo/bin/natls
Error: Os {code: 13, kind: PermissionDenied, message: "Permission denied"}
```
When I enter the ~/.cargo/bin/ directory, the execution will succeed
```
$ natls
rwxrwxr-x 8.16 MB Oct 27 06:05:12 yanqing yanqing natls
```
Thanks for any reply

**Comment by willdoescode** [comment]
you don't need to do ~/.cargo/bin/natls to execute nat, cargo install should automatically link the binary to your path meaning that from any directory you should be able to type natls and it will work. If permission is still denied than write 
```bash
sudo natls
```
to give nat permissions to view the contents of that directory.
