### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:280:3

### ISSUE THREAD

**Issue by saurabhwahile** [willdoescode/nat#39]
I can see my  directory when I'm in the $HOME/cargo/.bin path

But when I'm outside or any other path other that the path where the natls binary is present, this error is thrown 

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:280:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by willdoescode** [comment]
pushing a fix for it right now, for some reason your file did not have a user in the metadata.

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/commit/a5174ec1066380615a51418abbbc2638dcdb33ea

**Comment by saurabhwahile** [comment]
Thanks!
