### ISSUE TITLE
Add information that `nat` binary from releases page is a macOS executable

### ISSUE THREAD

**Issue by ElectronicWar** [willdoescode/nat#4]
The tool seems to be made for Linux machines from the Readme, but the provided executable is a macOS binary.

`nat: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>`

**Comment by gilly42** [comment]
But it didnt work well on OSX, or is it only my machine?

**Comment by dzschille** [comment]
Yes, an Linux binary would be nice. Just tried it with Ubuntu 20.04 and it told me that the binary has the wrong format.

**Comment by willdoescode** [comment]
will edit release to include this info
