### ISSUE TITLE
nat is no longer in the arch user repository

### ISSUE THREAD

**Issue by Gnarflord** [willdoescode/nat#42]
I've received this email on 10/27/2020, 10:46 PM UTC:
```
Foxboron [1] deleted nat-git [2].

You will no longer receive notifications about this package.

[1] https://aur.archlinux.org/account/Foxboron/
[2] https://aur.archlinux.org/pkgbase/nat-git/
```
I don't know the reason for this but I think the installation instructions for arch can be removed for now until another maintainer chooses to support this program.

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/commit/9f5a1cf773b2b6b291a9d14ba8f92ee7b87002c9

I am not sure why it's not working but for now I will just remove the installation instructions.
