### ISSUE TITLE
Does not work with watch

### ISSUE THREAD

**Issue by saurabhwahile** [willdoescode/nat#44]
This is an unusual use case, but sometimes I want to see large files being copied and their size growing.

I'd love to use `watch natls` for those times.

**Comment by willdoescode** [comment]
Are you asking to make it so that the file size dynamically increases on the screen?

**Comment by willdoescode** [comment]
the reason the output is gibberish is because nat is attempting to display color in the terminal witch watch does not seem to support, I will work on adding an option to disable color output so that you can read the watch output.

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/commit/b248580902feb2e9795890278f98599592c7b154
