### ISSUE TITLE
[proposal] homebrew installation

### ISSUE THREAD

**Issue by luiscobits** [willdoescode/nat#45]
What do you think about adding homebrew installation?

**Comment by willdoescode** [comment]
the nat repo is currently not 30 days old which is the minimum for homebrew. After nat is 30 days old I will definitely add it to homebrew.

**Comment by willdoescode** [comment]
I have added natls to homebrew
simply run
```brew tap willdoescode/homebrew-natls```
and then 
```brew install natls```
