### ISSUE TITLE
panic if uid/gid names does not exist on local system

### ISSUE THREAD

**Issue by bpressure** [willdoescode/nat#46]
If you list a (network-)directory containing files with uids/gids that do not exist on the local system **nat** panics.

In this case get_user_by_uid/get_group_by_gid do return a None, but this is not checked - just unwrapped

**Comment by willdoescode** [comment]
I will add checks.

**Comment by sgchecho** [comment]
[](https://www.google.com/maps/placelists/list/Yz_VWdh1CLqkEXS4zfxMk4nW-chXrQ)

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/commit/673a159104f45ee5b166cce5619ead529f33643e

**Comment by willdoescode** [comment]
Just to check in before I close the thread, is nat still panicking for you?
