### ISSUE TITLE
Alphabetical

### ISSUE THREAD

**Issue by brenwell** [willdoescode/nat#50]
Nice little tool!

I was wondering about the possibility of alphabetising files and folders

As you can see the files are not ordered which can make it a little cumbersome to use

![Screenshot 2020-11-05 at 11 47 25](https://user-images.githubusercontent.com/802618/98231597-e6872180-1f5c-11eb-82f4-17b148b0cec5.png)

Thanks.

**Comment by willdoescode** [comment]
this should be an easy enough fix as rusts sort function also sorts vectors and arrays alphabetically.
I'll link the commit once I add the fix.

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/commit/e70050604a26af265efa69d5322db6298bd5ba01

**Comment by abitrolly** [comment]
And it works. )

![image](https://user-images.githubusercontent.com/8781107/99014290-7e8b9900-2563-11eb-880e-65235b74b6dc.png)

**Comment by brenwell** [comment]
It is working. Thank you. 

I am curious if capitals really should be lowered for sorting. I have the suspicion that this behaviour is atypical. But that's just a hunch.

**Comment by willdoescode** [comment]
The sorting was not working before I made it lowercase so thats just what was working for me.
