### ISSUE TITLE
Snap release updates

### ISSUE THREAD

**Issue by Witteborn** [willdoescode/nat#51]
## The issue
The current release on snap does not match the actual version.

## Reproduce
- install via "sudo snap install natls"
- check version of nat with "natls --version"

## Things I tried
- update nat with "sudo snap refresh natls"

## Idea for a fix
Snap should be integrated into a CI like GitHub Actions, Jenkins or similar to automatically update the binary. Or on each release someone should update the binary manually.

**Comment by abitrolly** [comment]
The snap is maintained by @tbille in https://github.com/tbille/natls-snap

Most likely Snap Store builds it automatically. It is possible to build directly from this repo instead, but then the `snapcraft.yml` should be committed here and @willdoescode need to register at the store and it add webhook to the repo.

**Comment by willdoescode** [comment]
I am working out getting natls updated on snap

**Comment by tbille** [comment]
Hey @willdoescode I am happy to make a pull request on your repo and handover the snap.

**Comment by willdoescode** [comment]
That would be great thank you

**Comment by willdoescode** [comment]
snapcraft should be on the latest version now! Now that I own the snap project I will push new builds before I add the build to github.

**Comment by abitrolly** [comment]
Awesome.

@tbille thanks for providing it in the first place.

**Comment by willdoescode** [comment]
yes thank you @tbille
