### ISSUE TITLE
Relative timestamps

### ISSUE THREAD

**Issue by abitrolly** [willdoescode/nat#54]
An example, how it looks in `ls++`.

![image](https://user-images.githubusercontent.com/8781107/99015306-ba276280-2565-11eb-8b6f-91609ff052af.png)

**Comment by willdoescode** [comment]
how are the current timestamps not readable?

**Comment by willdoescode** [comment]
accidentally closed sorry.

**Comment by abitrolly** [comment]
Renamed. )

**Comment by willdoescode** [comment]
I don't think this is a needed change because you can sort by time right now. Sorting by time puts the last modified files in order going up. Because there is a option to sort by time I do not think this is a needed change.

**Comment by abitrolly** [comment]
It is just a convenience. Most timestamps on the web are relative nowadays.

![image](https://user-images.githubusercontent.com/8781107/99016206-a7159200-2567-11eb-954b-a0f0405aa3c4.png)

**Comment by abitrolly** [comment]
Gmail also cuts down the amount of information printed. Maybe not relative, but more readable for humans, who usually don't need a second accurancy on daily+ intervals.
![image](https://user-images.githubusercontent.com/8781107/99016303-e217c580-2567-11eb-8a93-c24b5c76eb4c.png)

implementing this will probably require `-f` `--full` option to get back exact data.

**Comment by willdoescode** [comment]
I think I will have the exact data on by default and maybe a flag to enable relative time. I could probably implement it with https://docs.rs/chrono/0.4.0/chrono/struct.DateTime.html#method.signed_duration_since.

**Comment by abitrolly** [comment]
It still doesn't convert timestamp to human verbs. I am not sure what is available for Rust. For JavaScript there are plenty of alternatives https://www.npmjs.com/search?q=human%20readable%20time
