### ISSUE TITLE
Endless loop printing whitespaces

### ISSUE THREAD

**Issue by TilBlechschmidt** [willdoescode/nat#55]
When listing some folders, `natls` starts by printing the folder contents but then goes on to print infinite whitespaces.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/5037967/99396830-83917500-28e2-11eb-88e0-463be8cafda7.png">
I'm not quite sure what causes this but it is always the same folders (i.e. if one folder does it once, it will do it every time).

The example above comes from the `examples/basic` folder of [this](https://github.com/open-telemetry/opentelemetry-rust) project.

I'm on macOS Big Sur, iTerm, zsh 5.8 (x86_64-apple-darwin20.0.0), rustc 1.47.0-nightly (6c8927b0c 2020-07-26), natls 1.2.11

**Comment by TilBlechschmidt** [comment]
Seems to be fixed with the latest rust toolchain and natls 1.2.12, I'll leave this here for you to acknowledge just in case there could be something else causing it for other users.

Feel free to close this issue 🙂

**Comment by willdoescode** [comment]
This was a subtraction error in the spaces before the size of the file which I fixed in the last update.
If anyone is still having issues they should simply run ```cargo install natls```
