### ISSUE TITLE
"nat" just prints endless underscores

### ISSUE THREAD

**Issue by b00lduck** [willdoescode/nat#6]
I checked out the code and built it with "cargo build --release".

Started the binary and it prints underscores forever.

The "Help" function (-h) works fine.

OS: Arch Linux 64bit

**Comment by b00lduck** [comment]
Duplicate of #5

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/issues/6#issuecomment-715333158 closing this thread.
