### ISSUE TITLE
V2.1.9 is not pushed to GitHub

### ISSUE THREAD

**Issue by timschmitz86** [willdoescode/nat#60]
Version 2.1.9 is not released to GitHub. this affected a non working Homebrew installation.
Homebrew tries to install 2.1.9 which is not released yet.

**Comment by willdoescode** [comment]
Oops I forgot to do that, I will definitely get it pushed today

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/releases/tag/v2.1.9
