### ISSUE TITLE
Searching for nonexistent file or directory returns Rust error

### ISSUE THREAD

**Issue by Devnol** [willdoescode/nat#65]
OS: macOS 11.1
shell: zsh
Terminal: Default
Application source: Homebrew
Cargo version: 1.49.0

Running `natls nonexistent_file` returns the following error:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/utils/get_group.rs:5:53

**Comment by willdoescode** [comment]
sorry for late reply. Ill get on that.

**Comment by willdoescode** [comment]
pushing new build right now.
https://github.com/willdoescode/nat/commit/2d18a215d3b15a0833df5013c7f06236af5ade9c

**Comment by willdoescode** [comment]
https://github.com/willdoescode/nat/releases/tag/v2.1.10

**Comment by willdoescode** [comment]
![Screen Shot 2021-02-04 at 14 04 58](https://user-images.githubusercontent.com/53620720/106961105-f8aa6480-66f1-11eb-8325-b0dd8df4e29e.png)
its all done.
