### ISSUE TITLE
Group and date joined together

### ISSUE THREAD

**Issue by ysdexlic** [willdoescode/nat#70]
Group and date don't seem to have a gap between them, see screenshot below:

![Screenshot 2021-02-26 at 10 16 34](https://user-images.githubusercontent.com/16815919/109289039-896def00-781d-11eb-90f4-3fe5fadd29db.png)

This is with version `2.1.11`

**Comment by willdoescode** [comment]
Is that the only directory where that happens or does it happen in every directory?

**Comment by ysdexlic** [comment]
It's every directory

**Comment by willdoescode** [comment]
thats interesting, I haven't seen that happen before. Do you think that you could try re installing nat and see if the issue persists?

**Comment by ysdexlic** [comment]
Uninstalled and re-installed 3 times and it's still happening

**Comment by ysdexlic** [comment]
Currently on mobile and away from my laptop so can't be as helpful, but it looks like on line 420 in main.rs the blue color is where user should be and should instead be one set of brackets over.

Currently looks like:
```rs
writeln!(f, "{} {green}{} {yellow}{} {blue} {}{} {}",
```

Should look like:
```rs
writeln!(f, "{} {green}{} {yellow}{} {} {blue}{} {}",
```

**Comment by willdoescode** [comment]
Ill look at the positioning

**Comment by denysvitali** [comment]
Can you try again? #72 should have fixed this problem

**Comment by willdoescode** [comment]
I've pushed new builds to crates.io and homebrew and I'm doing a snapcraft build right now.
