### ISSUE TITLE
Better info description in README

### ISSUE THREAD

**Issue by qx-775** [willdoescode/nat#74]
Hi,

It's good that you updated the README.md for a fresh look.
As a user not knowing what natls does, it's not clear what it is, what it does fix and what it's written in (rust) and why.

Maybe add in the first sentence under the title what natls (_an alternative to ls with colors written in rust, being superfast!_) or something like that.
Maybe add some speed test **benchmark** `natls` vs `ls` and `lsd` and `exa`

You have to **sell** this program a bit if you want people to use it. Why do they want to use it? :)

Also, maybe give some **examples**:
` natls -l -m ` shows what the screenshot does, I believe
Anyways what do you think?

**Comment by willdoescode** [comment]
I feel as though it is already pretty clear about what natls does because of the picture and the description under it as well as the description of the repo itself.

**Comment by aidenybai** [comment]
I think a benchmark could be interesting

**Comment by qx-775** [comment]
And what about a table of contents?
As a user I just want to find the tool and quickly find a way to install without scrolling or Ctrl+f because I'm lazy. Or maybe allow a button with title [install] at the top of the README.

As for your comment, I disagree. Looking at most programs [lsd](https://github.com/Peltoche/lsd) has a description. [exa](https://github.com/ogham/exa) even has a short one liner: "A modern alternative for _ls_" which makes it very clear what it does.

**Comment by willdoescode** [comment]
I do provide installation instructions as well as a description in the repo description

**Comment by aidenybai** [comment]
> And what about a table of contents?
> As a user I just want to find the tool and quickly find a way to install without scrolling or Ctrl+f because I'm lazy. Or maybe allow a button with title [install] at the top of the README.
> 
> As for your comment, I disagree. Looking at most programs [lsd](https://github.com/Peltoche/lsd) has a description. [exa](https://github.com/ogham/exa) even has a short one liner: "A modern alternative for _ls_" which makes it very clear what it does.
> 
> You are ofcourse the main decision maker on this point but what do other think? Should natls have a short description? :)

I think Github already provides a built-in table of contents, and I think the tagline is "`ls` alternative with useful info and a splash of color 🎨" and that's pretty clear in the Github description

**Comment by willdoescode** [comment]
I think we probably have everything that we need in the readme right now so I am going to close this.
